##### Creating Variables

In [1]:
import tensorflow as tf

### TensorFlow Basics

##### Defining Variables and constant

In [2]:
a = tf.Variable([23])
print(a)
print(a.numpy())

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([23])>
[23]


In [3]:
###reassigning variables
print(a)
print()
print()
a.assign([74])
print(a)

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([23])>


<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([74])>


In [4]:
boolean_variables = tf.Variable([False,True,False])
print(boolean_variables)
print()
print(boolean_variables.numpy())

<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([False,  True, False])>

[False  True False]


In [5]:
###Get even in range(1,100)

num = tf.constant(100)
for i in range(1,num):
    if i%tf.constant(2)==0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


##### Creating tensors, adding, subtracting, multiplying, updating tensors, reshaping

In [6]:
x = tf.Variable([[1,2],
                [3,8]])
x = tf.convert_to_tensor(x)

In [7]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 8]])>

In [8]:
x1 = tf.add(x,10)
x1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 18]])>

In [9]:
tf.matmul(x,x1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 37,  48],
       [137, 180]])>

In [10]:
print(x)
print()
print()
print(tf.reshape(x1,([1,4])).numpy())

tf.Tensor(
[[1 2]
 [3 8]], shape=(2, 2), dtype=int32)


[[11 12 13 18]]


##### Fizz Buzz with TensorFlow

In [11]:
def num(number):
    no = tf.constant(number)
    for i in range(1,no+1):
        i = tf.constant(i)
        if i%3==0 and i%5==0:
            print('FizzBuzz')
        elif i%3==0:
            print('Fuzz')
        elif i%5==0:
            print('Buzz')
        else:
            print(i.numpy())

In [12]:
num(15)

1
2
Fuzz
4
Buzz
Fuzz
7
8
Fuzz
Buzz
11
Fuzz
13
14
FizzBuzz
